version: 2
jobs:
  checkout:
    docker:
    - image: circleci/node:8.15
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-yarn-sha-{{ checksum "yarn.lock" }}
        - v2-yarn-sha-
    - run:
        name: Install js dependencies
        command: yarn
    - run:
        name: Should not have any git not staged
        command: git diff --exit-code
    - save_cache:
        key: v2-yarn-sha-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn/v4
  test_unit:
    docker:
    - image: circleci/node:8.15
    steps:
    - checkout
    - install_js
    - run:
        name: Tests fake browser
        command: yarn test
    - run:
        name: Tests fake browser
        command: yarn test --coverage
    - run:
        name: Check coverage generated
        command: |
          if ! [[ -s coverage/lcov.info ]]
          then
            exit 1
          fi
workflows:
  version: 2
  pipeline:
    jobs:
    - checkout:
        filters:
          branches:
            ignore:
            - l10n
            - /dependabot\//
    - test_unit:
        requires:
        - checkout