version: 2
jobs:
  checkout:
    # working_directory: /src
    docker:
    - image: circleci/node:8.15
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-yarn-sha-{{ checksum "yarn.lock" }}
        - v2-yarn-sha-
    - run:
        name: Install js dependencies
        command: yarn
    - run:
        name: Should not have any git not staged
        command: git diff --exit-code
    - run:
        name: Check for duplicated packages
        command: yarn deduplicate
    - save_cache:
        key: v2-yarn-sha-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn/v4
workflows:
  version: 2
  pipeline:
    jobs:
    - checkout:
        filters:
          branches:
            ignore:
            - l10n
            - /dependabot\//